name: "Welcome & Hello"
on: [push]

jobs:
  build:
    name: Welcome
    runs-on: ubuntu-latest
    steps:
      # Any action that runs from the same repo needs checkout. If the action
      # Lived in a separate repo this would not be needed
      - uses: actions/checkout@v1
        with:
          # Shallow clone
          fetch-depth: 1
      - run: npm install
      - run: npm start
